### ISSUE TITLE
Problem att köra rake db:migrate, db:seed och db:setup

### ISSUE THREAD

**Issue by ch222kv** [latana/1DV450_ms223eq#6]
När jag kör rake db:migrate, db:seed eller db:setup så får jag felmeddelandet 

```
rake aborted!
TZInfo::DataSourceNotFound: No source of timezone data could be found.
Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving th
is error.
c:/Users/~~~~~~~/School/1DV450/Peer Review/latana/1DV450_ms223eq-1.0/1DV450_ms22
3eq-1.0/Webbramverk_Labb_1/config/environment.rb:5:in `<top (required)>'
TZInfo::ZoneinfoDirectoryNotFound: None of the paths included in TZInfo::Zoneinf
oDataSource.search_path are valid zoneinfo directories.
c:/Users/~~~~/School/1DV450/Peer Review/latana/1DV450_ms223eq-1.0/1DV450_ms22
3eq-1.0/Webbramverk_Labb_1/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
(See full trace by running task with --trace)
```

**Comment by ch222kv** [comment]
Problemet kan man undvika genom att ta bort platform delen av `gem 'tzinfo-data'` i Gemfile då jag kör x64 och inte x86.

**Comment by 1dv450** [comment]
Verkar vara bundet till windowsanvändare och uppkommer inte på mac. Men bra att tänka på :+1:
